### ISSUE TITLE
Allow soynode.render parameters to be functions that receive file buffer as argument

### ISSUE THREAD

**Issue by Robert-Frampton** [eduardolundgren/gulp-soynode#12]
Currently this is how `soynode.render` receives arguments.

```js
  var rendered = soynode.render(
    namespace + '.soyweb',
    optionsInternal.renderSoyWebContext,
    optionsInternal.renderSoyWebInjectedData,
    optionsSoynode.locales ? optionsSoynode.locales[0] : null
  );
```

It would be nice if `renderSoyWebContext` (and possibly the other args) could be a function that receives the `file` buffer as an argument and returns the value. That way you could do something like the following...

```js
return gulp.src('src/**/*.soy', {
	.pipe(frontMatter())
	.pipe(soynode({
		renderSoyWeb: true,
		renderSoyWebContext: function(file) {
			return {
				frontMatter: file.frontMatter
			}
		}
	}))
	.pipe(gulp.dest('dist'));
```

This is a pattern I've seen with many other [gulp plugins](https://www.npmjs.com/package/gulp-consolidate#data) for templates, and it would nice to use here.

**Comment by mairatma** [comment]
Sure, this now works for both `renderSoyWebContext` and `renderSoyWebInjectedData`.

I've pushed this but I don't have permission to publish it though. @eduardolundgren could you publish this new version to npm?

**Comment by Robert-Frampton** [comment]
Hey @eduardolundgren, any chance you could publish 1.5.3 soon?

**Comment by eduardolundgren** [comment]
Just added @mairatma as contributor there so she can push it.

**Comment by Robert-Frampton** [comment]
👍

**Comment by mairatma** [comment]
Done :)
