### ISSUE TITLE
Example gives build error

### ISSUE THREAD

**Issue by thomthom** [eduardolundgren/gulp-soynode#8]
```
    "gulp": "^3.9.1",
    "gulp-soynode": "^1.5.1"
```

When I try to use the example from the description, after using the `build-lang` command to build the `xlf` file and generating a translated version:

```
ar gulp = require('gulp');
var soynode = require('gulp-soynode');
 
gulp.task('build', function() {
  gulp.src('views/*.soy')
    .pipe(soynode({
      locales: ['en', 'pt-BR'],
        messageFilePathFormat: 'translations/translations_{LOCALE}.xlf'
    }))
    .pipe(gulp.dest('build'));
});
```

I would get an error:

```
λ gulp build
[14:05:45] Using gulpfile ~\Desktop\gulp\gulpfile.js
[14:05:45] Starting 'build'...
[14:05:45] Finished 'build' after 18 ms
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\tmp\soynode\build\simple_de.soy.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at C:\Users\tthomas2\Desktop\gulp\node_modules\gulp-soynode\index.js:129:24
    at Array.forEach (native)
    at C:\Users\tthomas2\Desktop\gulp\node_modules\gulp-soynode\index.js:121:15
    at Array.forEach (native)
    at EventEmitter.<anonymous> (C:\Users\tthomas2\Desktop\gulp\node_modules\gulp-soynode\index.js:118:11)
    at EventEmitter.g (events.js:260:16)
    at emitTwo (events.js:87:13)
```

1. I notice that `c:\tmp\soynode` has a `views` folder - not a `build` folder which it appear to try to read from.
2. If I change `.pipe(gulp.dest('build'));` to `.pipe(gulp.dest('views'));` then I get the js files copied back into my source `view` folder - which is not where I want them.
3. I haven't been able to figure out how to control the location of the temp folder - I don't want gulp-soynode to create a `tmp` folder in the root of `C:`.

Any ideas why the example yields errors?

**Comment by mairatma** [comment]
I can't seem to reproduce your problem, I've just tried the example you gave and it worked as expected, with no errors.

Could you maybe create a repo with the code you have that throws this error, with the soy files and translation files you're using, so we can try to reproduce?

**Comment by thomthom** [comment]
Sure thing. Here's the test repo: https://github.com/thomthom/test-gulp-soy

It's basically a combination of the Google Soy examples - and the examples from this repo.

I'm using Windows 10 - if that is of any significance.

Node: 4.4.4
Gulp: 3.9.1

**Comment by mairatma** [comment]
Thanks a lot, I can reproduce now and know what's causing this, will submit a fix soon :)

**Comment by thomthom** [comment]
Thank you very much for looking into this - and the fix.

Sidenote: is the temporary location configurable?

**Comment by mairatma** [comment]
It is, you can pass the `outputDir` option, which is `/tmp/soynoyde` by default.

**Comment by thomthom** [comment]
Any rough estimate to when this will be published?

**Comment by mairatma** [comment]
Could you publish a new version @eduardolundgren? I don't have the necessary permissions :)

**Comment by eduardolundgren** [comment]
Done.

**Comment by thomthom** [comment]
Perfect! Updated and now it builds just fine. Thank you very much for looking into this and providing a fix so fast. Really appreciate it.
